Algeria:
  name: Ulrich Atz
  status: In
Argentina:
  name: Ulrich Atz
  status: In
Australia:
  name: Ulrich Atz
  status: In
Belgium:
  name: Ulrich Atz
  status: In
Bosnia and Herzegovina:
  name: Ulrich Atz
  status: In
Brazil:
  name: Ulrich Atz
  status: In
Cameroon:
  name: Ulrich Atz
  status: In
Chile:
  name: Ulrich Atz
  status: In
Colombia:
  name: Ulrich Atz
  status: In
Costa Rica:
  name: Ulrich Atz
  status: In
Croatia:
  name: Ulrich Atz
  status: In
Ecuador:
  name: Ulrich Atz
  status: In
England:
  name: Ulrich Atz
  status: In
France:
  name: Ulrich Atz
  status: In
Germany:
  name: Ulrich Atz
  status: In
Ghana:
  name: Ulrich Atz
  status: In
Greece:
  name: Ulrich Atz
  status: In
Honduras:
  name: Ulrich Atz
  status: Out
Iran:
  name: Ulrich Atz
  status: In
Italy:
  name: Ulrich Atz
  status: In
Ivory Coast:
  name: Ulrich Atz
  status: In
Japan:
  name: Ulrich Atz
  status: In
Mexico:
  name: Ulrich Atz
  status: In
Netherlands:
  name: Ulrich Atz
  status: In
Nigeria:
  name: Ulrich Atz
  status: In
Portugal:
  name: Ulrich Atz
  status: In
Russia:
  name: Ulrich Atz
  status: In
South Korea:
  name: Ulrich Atz
  status: In
Spain:
  name: Ulrich Atz
  status: In
Switzerland:
  name: Ulrich Atz
  status: In
United States:
  name: Ulrich Atz
  status: In
Uruguay:
  name: Ulrich Atz
  status: In
